export const data = [
  {
    image: "https://robohash.org/aspernaturmolestiasvoluptas.png?size=100x100&set=set1",
    name: "Darcie Whitmell",
    color: "Mauv",
    hex_color: "#efa0c9",
    money: "$889.58",
    mobile: "Android 8.0, EMUI 8",
  },
  { image: "https://robohash.org/rerumvelquod.png?size=100x100&set=set1", name: "Harriett Frango", color: "Crimson", hex_color: "#464b51", money: "$372.19", mobile: "Android 2.2" },
  { image: "https://robohash.org/repellatconsequaturaut.png?size=100x100&set=set1", name: "Janessa Bernet", color: "Khaki", hex_color: "#7d3a9f", money: "$786.07", mobile: "Android 4.1" },
  { image: "https://robohash.org/autperspiciatisvoluptatem.png?size=100x100&set=set1", name: "Aland Geere", color: "Puce", hex_color: "#5d5286", money: "$541.89", mobile: "Feature phone" },
  {
    image: "https://robohash.org/animiillumaperiam.png?size=100x100&set=set1",
    name: "Dukey Autry",
    color: "Mauv",
    hex_color: "#104c04",
    money: "$333.34",
    mobile: "Microsoft Windows Mobile 6.5 Professional",
  },
  {
    image: "https://robohash.org/rerumsedet.png?size=100x100&set=set1",
    name: "Erroll Biggerdike",
    color: "Crimson",
    hex_color: "#a9d3eb",
    money: "$628.03",
    mobile: "Android 5.0.1, up to 6.0.1, Sense UI",
  },
  { image: "https://robohash.org/eligendieosvoluptas.png?size=100x100&set=set1", name: "Collen Gallichiccio", color: "Violet", hex_color: "#182d17", money: "$608.15", mobile: "Android 4.2.2" },
  { image: "https://robohash.org/idfugitconsectetur.png?size=100x100&set=set1", name: "Si Zum Felde", color: "Purple", hex_color: "#0d7a3b", money: "$161.27", mobile: "Android 4.4.2" },
  { image: "https://robohash.org/quibusdambeataeiusto.png?size=100x100&set=set1", name: "Horst Trassler", color: "Yellow", hex_color: "#2c0045", money: "$638.04", mobile: "Feature phone" },
  { image: "https://robohash.org/nondoloribusmollitia.png?size=100x100&set=set1", name: "Reggi Hysom", color: "Fuscia", hex_color: "#caad28", money: "$974.13", mobile: "Android 4.1, up to 4.4.2" },
  { image: "https://robohash.org/eteumperferendis.png?size=100x100&set=set1", name: "Lari Blower", color: "Red", hex_color: "#a2dd9e", money: "$950.01", mobile: "Android 5.0, up to 6.0" },
  { image: "https://robohash.org/quirerumsuscipit.png?size=100x100&set=set1", name: "Garrick Tremontana", color: "Violet", hex_color: "#3cd4c4", money: "$279.51", mobile: "Android 2.3" },
  { image: "https://robohash.org/aliquamrepellataut.png?size=100x100&set=set1", name: "Gypsy Speedy", color: "Goldenrod", hex_color: "#9436b4", money: "$309.41", mobile: "Android 6, nubia UI 4" },
  { image: "https://robohash.org/doloressedvelit.png?size=100x100&set=set1", name: "Jaquith Wavell", color: "Green", hex_color: "#531516", money: "$36.24", mobile: "iOS 4, up to iOS 7.1.1" },
  { image: "https://robohash.org/quodquobeatae.png?size=100x100&set=set1", name: "Estrellita Giggie", color: "Green", hex_color: "#b1cf60", money: "$254.96", mobile: "Android 2.3" },
  { image: "https://robohash.org/fugitdeseruntquam.png?size=100x100&set=set1", name: "Jo Pill", color: "Puce", hex_color: "#28b061", money: "$638.58", mobile: "Feature phone" },
  { image: "https://robohash.org/maioressintmolestiae.png?size=100x100&set=set1", name: "Marilee Bosence", color: "Mauv", hex_color: "#3e776b", money: "$706.99", mobile: "Android 8.1, EMUI 8.2" },
  { image: "https://robohash.org/nequeoptioeius.png?size=100x100&set=set1", name: "Drusy Bracey", color: "Maroon", hex_color: "#573901", money: "$5.09", mobile: "Android 4.4.2" },
  {
    image: "https://robohash.org/estvoluptatemquis.png?size=100x100&set=set1",
    name: "Carmencita Kemish",
    color: "Purple",
    hex_color: "#1dee65",
    money: "$512.37",
    mobile: "Android 9.0, up to Android 10, LG UX 9",
  },
  { image: "https://robohash.org/liberomodinumquam.png?size=100x100&set=set1", name: "Nonnah O'Concannon", color: "Crimson", hex_color: "#116962", money: "$954.73", mobile: "Android 10, MIUI 11" },
  { image: "https://robohash.org/quosullamimpedit.png?size=100x100&set=set1", name: "Meagan Sousa", color: "Puce", hex_color: "#d9899a", money: "$73.61", mobile: "Feature phone" },
  {
    image: "https://robohash.org/repellatnesciuntneque.png?size=100x100&set=set1",
    name: "Rafa Pocknoll",
    color: "Khaki",
    hex_color: "#4c9be4",
    money: "$580.05",
    mobile: "Android 9.0, up to Android 10, LG UX 10.0",
  },
  { image: "https://robohash.org/voluptatibusautquos.png?size=100x100&set=set1", name: "Selle Walby", color: "Violet", hex_color: "#fb6ada", money: "$914.14", mobile: "Android 4.1" },
  { image: "https://robohash.org/blanditiisquisquamquaerat.png?size=100x100&set=set1", name: "Cindee Hancox", color: "Violet", hex_color: "#acfecd", money: "$350.91", mobile: "Linux, JUIX UI" },
  {
    image: "https://robohash.org/temporibuscommodivoluptatem.png?size=100x100&set=set1",
    name: "Dolph Scandrett",
    color: "Orange",
    hex_color: "#77f71e",
    money: "$496.38",
    mobile: "Android 9.0, ColorOS 6",
  },
  {
    image: "https://robohash.org/insuntipsum.png?size=100x100&set=set1",
    name: "Jodie Sprigg",
    color: "Orange",
    hex_color: "#2264b6",
    money: "$840.06",
    mobile: "Android 4.4.2, up to 6.0, TouchWiz UI",
  },
  { image: "https://robohash.org/faceresuntet.png?size=100x100&set=set1", name: "Abbe Woodeson", color: "Pink", hex_color: "#3dd55e", money: "$329.23", mobile: "Android 2.3.5, up to 4.1.2" },
  { image: "https://robohash.org/inventoreconsequaturlibero.png?size=100x100&set=set1", name: "Merrili Pleasance", color: "Pink", hex_color: "#763b85", money: "$285.44", mobile: "Android 7.0" },
  {
    image: "https://robohash.org/excepturiquiserror.png?size=100x100&set=set1",
    name: "Leonerd Demkowicz",
    color: "Orange",
    hex_color: "#eb2ac3",
    money: "$224.94",
    mobile: "Android 9.0, ColorOS 6.1",
  },
  {
    image: "https://robohash.org/autemaccusamusiure.png?size=100x100&set=set1",
    name: "Stan Roscam",
    color: "Turquoise",
    hex_color: "#5237db",
    money: "$509.11",
    mobile: "Android 4.4.2, TouchWiz Essence UI",
  },
  { image: "https://robohash.org/perspiciatistotamdoloribus.png?size=100x100&set=set1", name: "Guntar Maharey", color: "Orange", hex_color: "#25b99c", money: "$630.85", mobile: "Feature phone" },
  { image: "https://robohash.org/nesciunttemporibusaut.png?size=100x100&set=set1", name: "Lionello Cossar", color: "Turquoise", hex_color: "#688330", money: "$209.56", mobile: "Feature phone" },
  { image: "https://robohash.org/vitaeestomnis.png?size=100x100&set=set1", name: "Jarib Owen", color: "Teal", hex_color: "#600d52", money: "$977.86", mobile: "Android 5.0, up to 5.1.1" },
  { image: "https://robohash.org/occaecatieossapiente.png?size=100x100&set=set1", name: "Skyler Redmore", color: "Green", hex_color: "#65363d", money: "$698.29", mobile: "Feature phone" },
  { image: "https://robohash.org/nostrumipsamexplicabo.png?size=100x100&set=set1", name: "Emera Dorning", color: "Fuscia", hex_color: "#8f8c02", money: "$483.33", mobile: "Android 2.3.6" },
  {
    image: "https://robohash.org/enimnostrumdolorum.png?size=100x100&set=set1",
    name: "Jasun Everington",
    color: "Yellow",
    hex_color: "#a70eae",
    money: "$787.76",
    mobile: "Android 10, EMUI 10, no Google Play Services",
  },
  { image: "https://robohash.org/doloresquasexplicabo.png?size=100x100&set=set1", name: "Riva Wackett", color: "Pink", hex_color: "#fcd129", money: "$35.11", mobile: "Android 2.3" },
  { image: "https://robohash.org/quibusdamlaborumfugit.png?size=100x100&set=set1", name: "Gearalt Lergan", color: "Aquamarine", hex_color: "#160663", money: "$746.76", mobile: "Feature phone" },
  { image: "https://robohash.org/autnihilquia.png?size=100x100&set=set1", name: "Peder McKniely", color: "Orange", hex_color: "#1cfa04", money: "$604.26", mobile: "Symbian OS 9.2, S60 rel. 3.1" },
  { image: "https://robohash.org/voluptatemipsamodio.png?size=100x100&set=set1", name: "Tony Johanssen", color: "Turquoise", hex_color: "#8ff087", money: "$487.45", mobile: "Feature phone" },
  { image: "https://robohash.org/excepturiearumpariatur.png?size=100x100&set=set1", name: "Federica Astling", color: "Puce", hex_color: "#ae8296", money: "$43.15", mobile: "Android 8.1 Oreo" },
  { image: "https://robohash.org/autveritatisqui.png?size=100x100&set=set1", name: "Marybelle Belliss", color: "Yellow", hex_color: "#bc7b2b", money: "$43.21", mobile: "bada 1.2, TouchWiz UI 3" },
  { image: "https://robohash.org/facilisquiasequi.png?size=100x100&set=set1", name: "Tybie Northway", color: "Fuscia", hex_color: "#746869", money: "$333.55", mobile: "Android 9.0, MIUI 11" },
  { image: "https://robohash.org/quiaquiavoluptatem.png?size=100x100&set=set1", name: "Eb Batch", color: "Indigo", hex_color: "#d6caa8", money: "$804.55", mobile: "Android 1.5, up to 2.1 in USA" },
  { image: "https://robohash.org/necessitatibusabnumquam.png?size=100x100&set=set1", name: "Durward Karolewski", color: "Blue", hex_color: "#25ea1e", money: "$657.52", mobile: "Feature phone" },
  { image: "https://robohash.org/omnisrepudiandaeet.png?size=100x100&set=set1", name: "Kiah Scawton", color: "Indigo", hex_color: "#739b31", money: "$347.36", mobile: "Android 10, HIOS 6.0" },
  { image: "https://robohash.org/eumimpeditullam.png?size=100x100&set=set1", name: "Millard Blackbrough", color: "Goldenrod", hex_color: "#ae5197", money: "$956.63", mobile: "Android 2.2, Sense UI" },
  { image: "https://robohash.org/utvoluptatesipsa.png?size=100x100&set=set1", name: "Faith Janusz", color: "Orange", hex_color: "#cfd162", money: "$830.27", mobile: "Feature phone" },
  { image: "https://robohash.org/delenitietsit.png?size=100x100&set=set1", name: "Collen Spearing", color: "Purple", hex_color: "#5183e6", money: "$190.62", mobile: "Android 7.0, up to Android 8.0" },
  { image: "https://robohash.org/officiaofficiisaperiam.png?size=100x100&set=set1", name: "Juan Tourner", color: "Crimson", hex_color: "#7aa445", money: "$584.38", mobile: "Feature phone" },
  {
    image: "https://robohash.org/velitporrovel.png?size=100x100&set=set1",
    name: "Raven Hulbert",
    color: "Indigo",
    hex_color: "#c78c1f",
    money: "$732.27",
    mobile: "Microsoft Windows Mobile 6.5 Professional",
  },
  {
    image: "https://robohash.org/oditvoluptatemrerum.png?size=100x100&set=set1",
    name: "Keen Gillion",
    color: "Aquamarine",
    hex_color: "#ead476",
    money: "$450.63",
    mobile: "Microsoft Windows Mobile 5.0 Smartphone",
  },
  { image: "https://robohash.org/eterrormaxime.png?size=100x100&set=set1", name: "Burgess Branchflower", color: "Puce", hex_color: "#08d535", money: "$699.28", mobile: "Android 7.0" },
  { image: "https://robohash.org/utquiaprovident.png?size=100x100&set=set1", name: "Kahaleel Stainson", color: "Blue", hex_color: "#434a02", money: "$354.67", mobile: "Feature phone" },
  { image: "https://robohash.org/autnisisint.png?size=100x100&set=set1", name: "Antonietta Ducker", color: "Pink", hex_color: "#849632", money: "$611.08", mobile: "Android 10, Realme UI" },
  { image: "https://robohash.org/eumvoluptatumeos.png?size=100x100&set=set1", name: "Aggy Crissil", color: "Pink", hex_color: "#5fea15", money: "$240.33", mobile: "Symbian, Series 90 UI, .2.0" },
  { image: "https://robohash.org/quiverosint.png?size=100x100&set=set1", name: "Rahal Norster", color: "Aquamarine", hex_color: "#4e9d87", money: "$788.67", mobile: "Android 5.1" },
  { image: "https://robohash.org/repellendusabdistinctio.png?size=100x100&set=set1", name: "Marja Newbury", color: "Orange", hex_color: "#dff8af", money: "$526.04", mobile: "Android 4.0.4" },
  { image: "https://robohash.org/etvoluptatibusaperiam.png?size=100x100&set=set1", name: "Renae Lorden", color: "Teal", hex_color: "#c413f0", money: "$561.23", mobile: "Android 4.0" },
  { image: "https://robohash.org/fugiatquirepudiandae.png?size=100x100&set=set1", name: "Elston Moles", color: "Teal", hex_color: "#49274d", money: "$657.54", mobile: "Android 5.1.1, up to 7.0" },
  {
    image: "https://robohash.org/maximetotamblanditiis.png?size=100x100&set=set1",
    name: "Jarid Fosdick",
    color: "Purple",
    hex_color: "#367035",
    money: "$932.91",
    mobile: "Android 4.4.2, TouchWiz UI",
  },
  { image: "https://robohash.org/mollitiatemporedolores.png?size=100x100&set=set1", name: "Carling Ansteys", color: "Goldenrod", hex_color: "#c4b7ab", money: "$710.85", mobile: "Feature phone" },
  { image: "https://robohash.org/veniameligenditenetur.png?size=100x100&set=set1", name: "Zaneta Moralas", color: "Violet", hex_color: "#c4b1e3", money: "$31.05", mobile: "Feature phone" },
  { image: "https://robohash.org/corporisipsumet.png?size=100x100&set=set1", name: "Murvyn Cissell", color: "Mauv", hex_color: "#e19db5", money: "$336.79", mobile: "Microsoft Smartphone 2003 SE" },
  { image: "https://robohash.org/undeetqui.png?size=100x100&set=set1", name: "Dwayne Winsley", color: "Fuscia", hex_color: "#def6b9", money: "$610.79", mobile: "Feature phone" },
  { image: "https://robohash.org/aspernaturetfacere.png?size=100x100&set=set1", name: "Norry Dumphries", color: "Green", hex_color: "#bea794", money: "$778.27", mobile: "Feature phone" },
  { image: "https://robohash.org/placeatdolorumsed.png?size=100x100&set=set1", name: "Conney Showering", color: "Fuscia", hex_color: "#61d67c", money: "$930.94", mobile: "Android 4.0.4" },
  { image: "https://robohash.org/namatqueofficia.png?size=100x100&set=set1", name: "Romeo Walder", color: "Green", hex_color: "#ec9703", money: "$107.24", mobile: "Feature phone" },
  { image: "https://robohash.org/temporeducimusofficia.png?size=100x100&set=set1", name: "Gusti Westcarr", color: "Red", hex_color: "#833ac0", money: "$329.70", mobile: "Android 7.0" },
  { image: "https://robohash.org/itaqueplaceatquis.png?size=100x100&set=set1", name: "Nikki Surgey", color: "Turquoise", hex_color: "#054f0b", money: "$463.84", mobile: "Android 8.1" },
  { image: "https://robohash.org/providentmagnieligendi.png?size=100x100&set=set1", name: "Oralee Lauthian", color: "Crimson", hex_color: "#d2bab7", money: "$840.82", mobile: "Android 4.2" },
  {
    image: "https://robohash.org/laborumaccusamusnon.png?size=100x100&set=set1",
    name: "Dore Tompkiss",
    color: "Blue",
    hex_color: "#b95f43",
    money: "$551.79",
    mobile: "Android 9.0, up to Android 11, One UI 3.0",
  },
  { image: "https://robohash.org/quibusdamnecessitatibusin.png?size=100x100&set=set1", name: "Juliet Dulake", color: "Fuscia", hex_color: "#076c7b", money: "$223.04", mobile: "Android 2.3.3" },
  { image: "https://robohash.org/distinctiodelectuseum.png?size=100x100&set=set1", name: "Valry Whitby", color: "Crimson", hex_color: "#45b2a6", money: "$507.96", mobile: "Feature phone" },
  { image: "https://robohash.org/sedautenim.png?size=100x100&set=set1", name: "Orville Carous", color: "Goldenrod", hex_color: "#ae44c6", money: "$977.15", mobile: "Android 4.2" },
  { image: "https://robohash.org/nequeexplicabomodi.png?size=100x100&set=set1", name: "Ade Thireau", color: "Aquamarine", hex_color: "#d8b13a", money: "$292.17", mobile: "Feature phone" },
  { image: "https://robohash.org/etetnesciunt.png?size=100x100&set=set1", name: "Cirilo Rupp", color: "Puce", hex_color: "#3cfc1b", money: "$616.23", mobile: "Feature phone" },
  { image: "https://robohash.org/temporibusrerumet.png?size=100x100&set=set1", name: "Shannan Halbard", color: "Blue", hex_color: "#2160c3", money: "$274.21", mobile: "Android 4.0" },
  { image: "https://robohash.org/quidemerrorquisquam.png?size=100x100&set=set1", name: "Jerome Rizon", color: "Indigo", hex_color: "#ab4f08", money: "$144.76", mobile: "Proprietary OS" },
  {
    image: "https://robohash.org/utullamlaudantium.png?size=100x100&set=set1",
    name: "Pietra Lavrinov",
    color: "Blue",
    hex_color: "#66eaad",
    money: "$673.41",
    mobile: "Android 9.0, up to Android 10, One UI 2.0",
  },
  { image: "https://robohash.org/iureplaceatab.png?size=100x100&set=set1", name: "Filmore Formoy", color: "Teal", hex_color: "#69f6b1", money: "$726.62", mobile: "Feature phone" },
  {
    image: "https://robohash.org/magnivoluptatemratione.png?size=100x100&set=set1",
    name: "Cristian Romaines",
    color: "Turquoise",
    hex_color: "#57f030",
    money: "$540.59",
    mobile: "Symbian^3, up to Nokia Belle OS",
  },
  {
    image: "https://robohash.org/erroriustofacere.png?size=100x100&set=set1",
    name: "Cher McGrill",
    color: "Purple",
    hex_color: "#c7732e",
    money: "$192.65",
    mobile: "Android 10, up to Android 11, One UI 3.1",
  },
  { image: "https://robohash.org/sintetaccusamus.png?size=100x100&set=set1", name: "Nanice Jinda", color: "Goldenrod", hex_color: "#fe9343", money: "$456.99", mobile: "Feature phone" },
  { image: "https://robohash.org/autmolestiaenumquam.png?size=100x100&set=set1", name: "Cate Dean", color: "Indigo", hex_color: "#92ea20", money: "$776.28", mobile: "Symbian 7.0, UIQ v2.1 UI" },
  {
    image: "https://robohash.org/hicrerumaperiam.png?size=100x100&set=set1",
    name: "Keefer Capstake",
    color: "Purple",
    hex_color: "#2b3e80",
    money: "$352.73",
    mobile: "Symbian OS 9.1, S60 3rd edition",
  },
  { image: "https://robohash.org/nobisquoprovident.png?size=100x100&set=set1", name: "Alonso Stoute", color: "Aquamarine", hex_color: "#ca1658", money: "$574.58", mobile: "Feature phone" },
  { image: "https://robohash.org/totamidnobis.png?size=100x100&set=set1", name: "Dionne Lagen", color: "Blue", hex_color: "#2bfe04", money: "$856.58", mobile: "Android 4.4.2" },
  { image: "https://robohash.org/illoetducimus.png?size=100x100&set=set1", name: "Darcy Pairpoint", color: "Fuscia", hex_color: "#e09ad5", money: "$267.41", mobile: "Android 6.0" },
  { image: "https://robohash.org/quisinciduntquo.png?size=100x100&set=set1", name: "Murial Goddert.sf", color: "Teal", hex_color: "#5ce907", money: "$63.58", mobile: "Android 6.0, eUI 5.8" },
  { image: "https://robohash.org/beataerepellendussed.png?size=100x100&set=set1", name: "Chlo Silcock", color: "Puce", hex_color: "#7bc7e2", money: "$347.14", mobile: "Android 4.0" },
  { image: "https://robohash.org/suscipitvoluptatuma.png?size=100x100&set=set1", name: "Terrye Espinazo", color: "Fuscia", hex_color: "#7c43e7", money: "$511.82", mobile: "Android 5.1.1, up to 7.0" },
  { image: "https://robohash.org/quienimet.png?size=100x100&set=set1", name: "Gawen Burdoun", color: "Purple", hex_color: "#5dc615", money: "$626.72", mobile: "Android 4.0" },
  { image: "https://robohash.org/sitquiet.png?size=100x100&set=set1", name: "Gaylene Girardin", color: "Aquamarine", hex_color: "#7125db", money: "$418.62", mobile: "Feature phone" },
  { image: "https://robohash.org/voluptatemverosuscipit.png?size=100x100&set=set1", name: "Augustine Whiteway", color: "Red", hex_color: "#3372d7", money: "$432.67", mobile: "Android 4.0" },
  { image: "https://robohash.org/ducimusexercitationemdolor.png?size=100x100&set=set1", name: "Corina Martinson", color: "Orange", hex_color: "#eada58", money: "$776.12", mobile: "Feature phone" },
  { image: "https://robohash.org/magnicommodiharum.png?size=100x100&set=set1", name: "Locke Josskovitz", color: "Green", hex_color: "#1b366b", money: "$183.36", mobile: "Feature phone" },
  { image: "https://robohash.org/fugiatdebitismolestias.png?size=100x100&set=set1", name: "Nancy Flowerden", color: "Orange", hex_color: "#086f26", money: "$699.66", mobile: "Feature phone" },
  { image: "https://robohash.org/autadaspernatur.png?size=100x100&set=set1", name: "Bobina Radclyffe", color: "Pink", hex_color: "#469fd8", money: "$265.69", mobile: "Feature phone" },
  {
    image: "https://robohash.org/asperioresquodet.png?size=100x100&set=set1",
    name: "Corine Hurran",
    color: "Green",
    hex_color: "#7c47ea",
    money: "$78.42",
    mobile: "Android 10, up to Android 11, One UI 3.1",
  },
  { image: "https://robohash.org/etlaudantiumvoluptas.png?size=100x100&set=set1", name: "Meade Browncey", color: "Turquoise", hex_color: "#ada666", money: "$457.09", mobile: "Android 5.0.1" },
  { image: "https://robohash.org/utametrem.png?size=100x100&set=set1", name: "Layney Lummasana", color: "Blue", hex_color: "#7e1c09", money: "$17.56", mobile: "Proprietary OS" },
  { image: "https://robohash.org/pariaturabaspernatur.png?size=100x100&set=set1", name: "Bianca Docharty", color: "Turquoise", hex_color: "#fb5136", money: "$217.56", mobile: "Android 4.2.2" },
  { image: "https://robohash.org/illorecusandaeenim.png?size=100x100&set=set1", name: "Dulsea Taphouse", color: "Maroon", hex_color: "#427766", money: "$102.33", mobile: "Feature phone" },
  { image: "https://robohash.org/enimofficiaquibusdam.png?size=100x100&set=set1", name: "Cymbre Di Domenico", color: "Green", hex_color: "#db3beb", money: "$720.77", mobile: "Feature phone" },
  { image: "https://robohash.org/esselaboreeligendi.png?size=100x100&set=set1", name: "Danielle Hearnaman", color: "Blue", hex_color: "#24d50c", money: "$217.78", mobile: "Android 10, One UI 2" },
  { image: "https://robohash.org/consequatureaillum.png?size=100x100&set=set1", name: "Julian Boustred", color: "Blue", hex_color: "#5209da", money: "$145.78", mobile: "Feature phone" },
  {
    image: "https://robohash.org/voluptatemasperioresearum.png?size=100x100&set=set1",
    name: "Bronson Millen",
    color: "Pink",
    hex_color: "#adc7e4",
    money: "$377.49",
    mobile: "Microsoft Windows Phone 8, Sense UI",
  },
  { image: "https://robohash.org/consequaturaspernaturet.png?size=100x100&set=set1", name: "Calla Syseland", color: "Orange", hex_color: "#cc306a", money: "$288.21", mobile: "Feature phone" },
  { image: "https://robohash.org/sedaliquamvoluptatem.png?size=100x100&set=set1", name: "Muhammad Annatt", color: "Khaki", hex_color: "#3299ee", money: "$619.93", mobile: "Android 2.3" },
  { image: "https://robohash.org/eiusatqueeligendi.png?size=100x100&set=set1", name: "Aida Dudding", color: "Puce", hex_color: "#c038b8", money: "$748.63", mobile: "Android 4.2" },
  { image: "https://robohash.org/quiomnisvoluptatibus.png?size=100x100&set=set1", name: "Verge Gerlack", color: "Purple", hex_color: "#f2c065", money: "$607.93", mobile: "Android 4.4.2, LG UI 3" },
  { image: "https://robohash.org/etautvelit.png?size=100x100&set=set1", name: "Loren Mebes", color: "Green", hex_color: "#1fac07", money: "$557.22", mobile: "Android 2.1" },
  { image: "https://robohash.org/aspernaturanimiquibusdam.png?size=100x100&set=set1", name: "Avril Nussii", color: "Mauv", hex_color: "#dd775f", money: "$251.19", mobile: "Android 7.0" },
  {
    image: "https://robohash.org/voluptasaccusamusipsa.png?size=100x100&set=set1",
    name: "Lonnie Spellworth",
    color: "Puce",
    hex_color: "#82e716",
    money: "$153.35",
    mobile: "Android 5.1, Funtouch 2.1",
  },
  { image: "https://robohash.org/etharumsunt.png?size=100x100&set=set1", name: "Kaleb Foker", color: "Turquoise", hex_color: "#4434cd", money: "$563.54", mobile: "Android 4.2.2, Sense UI 5.1" },
  { image: "https://robohash.org/ipsumesseut.png?size=100x100&set=set1", name: "Dyna Woodburne", color: "Green", hex_color: "#b13073", money: "$1.22", mobile: "Android 4.0" },
  { image: "https://robohash.org/sitiustohic.png?size=100x100&set=set1", name: "Mollie Coggings", color: "Khaki", hex_color: "#9f681c", money: "$626.27", mobile: "Feature phone" },
  { image: "https://robohash.org/explicabovelquasi.png?size=100x100&set=set1", name: "Kleon Bow", color: "Mauv", hex_color: "#8a3347", money: "$487.08", mobile: "Android 6.0, Amigo 3.2" },
  { image: "https://robohash.org/voluptasautblanditiis.png?size=100x100&set=set1", name: "Dionisio Crannell", color: "Yellow", hex_color: "#4fb45e", money: "$366.03", mobile: "Android 5.0" },
  { image: "https://robohash.org/doloresrationeducimus.png?size=100x100&set=set1", name: "Sosanna Fearfull", color: "Puce", hex_color: "#ffe7e0", money: "$496.62", mobile: "Feature phone" },
  {
    image: "https://robohash.org/quiutautem.png?size=100x100&set=set1",
    name: "Neely Binstead",
    color: "Khaki",
    hex_color: "#eb3ef1",
    money: "$751.79",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    image: "https://robohash.org/modidoloremquelabore.png?size=100x100&set=set1",
    name: "D'arcy Jakobssen",
    color: "Indigo",
    hex_color: "#128473",
    money: "$229.12",
    mobile: "Android 4.4 - EU model\r\n5.1",
  },
  { image: "https://robohash.org/eumexcepturiconsectetur.png?size=100x100&set=set1", name: "Gelya Smorthit", color: "Yellow", hex_color: "#fcb8ac", money: "$444.14", mobile: "Android 6.0" },
  { image: "https://robohash.org/rerumsitveritatis.png?size=100x100&set=set1", name: "Kingsly Trail", color: "Red", hex_color: "#02f36b", money: "$760.87", mobile: "Feature phone" },
  { image: "https://robohash.org/enimquoquis.png?size=100x100&set=set1", name: "Gannie Stienham", color: "Red", hex_color: "#c7685f", money: "$930.51", mobile: "Feature phone" },
  { image: "https://robohash.org/exercitationemvoluptatemperspiciatis.png?size=100x100&set=set1", name: "Zia Ledes", color: "Purple", hex_color: "#5928bf", money: "$370.64", mobile: "Android 6.0.1" },
  { image: "https://robohash.org/etprovidentsint.png?size=100x100&set=set1", name: "Diarmid Castiglioni", color: "Indigo", hex_color: "#9cdcd7", money: "$523.49", mobile: "Feature phone" },
  { image: "https://robohash.org/nisiassumendaqui.png?size=100x100&set=set1", name: "Sileas Henner", color: "Maroon", hex_color: "#667447", money: "$659.46", mobile: "Android 4.4.2" },
  { image: "https://robohash.org/voluptasautprovident.png?size=100x100&set=set1", name: "Brigida Colwell", color: "Purple", hex_color: "#5d5734", money: "$976.26", mobile: "Feature phone" },
  { image: "https://robohash.org/consecteturquiid.png?size=100x100&set=set1", name: "Rosina Iiannoni", color: "Maroon", hex_color: "#696d3e", money: "$490.02", mobile: "Android 7, nubia UI 4" },
  { image: "https://robohash.org/veleaquedolorum.png?size=100x100&set=set1", name: "Ardath Romain", color: "Fuscia", hex_color: "#79a663", money: "$321.30", mobile: "Microsoft Windows Phone 8.1" },
  { image: "https://robohash.org/saepequosit.png?size=100x100&set=set1", name: "Lonny Ragsdall", color: "Orange", hex_color: "#a3cb7b", money: "$197.20", mobile: "Feature phone" },
  {
    image: "https://robohash.org/idlaborumquibusdam.png?size=100x100&set=set1",
    name: "Teirtza Norker",
    color: "Goldenrod",
    hex_color: "#b9799b",
    money: "$33.07",
    mobile: "Microsoft Windows Phone 8.1",
  },
  { image: "https://robohash.org/architectorerumcupiditate.png?size=100x100&set=set1", name: "Tessy Ciotto", color: "Goldenrod", hex_color: "#397665", money: "$545.88", mobile: "Feature phone" },
  { image: "https://robohash.org/exvoluptasest.png?size=100x100&set=set1", name: "Turner McCauley", color: "Maroon", hex_color: "#fb57bd", money: "$165.57", mobile: "Android 4.2" },
  { image: "https://robohash.org/perferendisincidunterror.png?size=100x100&set=set1", name: "Elston Mewrcik", color: "Khaki", hex_color: "#e2a3b1", money: "$525.06", mobile: "Feature phone" },
  {
    image: "https://robohash.org/dignissimosipsumautem.png?size=100x100&set=set1",
    name: "Lorettalorna Wingeatt",
    color: "Indigo",
    hex_color: "#b9038b",
    money: "$303.48",
    mobile: "Android 8.1, up to Android 10, Android One",
  },
  { image: "https://robohash.org/etomnisaliquid.png?size=100x100&set=set1", name: "Meade Blease", color: "Pink", hex_color: "#7ac0ea", money: "$631.65", mobile: "Android 8.1, ColorOS 5.2" },
  { image: "https://robohash.org/accusamusvoluptatumquod.png?size=100x100&set=set1", name: "Kaylee Remon", color: "Indigo", hex_color: "#06fb71", money: "$980.63", mobile: "Android 4.2" },
  { image: "https://robohash.org/ducimuspariaturqui.png?size=100x100&set=set1", name: "Sarita McInulty", color: "Yellow", hex_color: "#788dfb", money: "$419.05", mobile: "Feature phone" },
  { image: "https://robohash.org/eosvelitcumque.png?size=100x100&set=set1", name: "Blake Linskill", color: "Turquoise", hex_color: "#eb3e02", money: "$789.09", mobile: "Feature phone" },
  { image: "https://robohash.org/quiaestexcepturi.png?size=100x100&set=set1", name: "Kathie Baggalley", color: "Maroon", hex_color: "#218eb8", money: "$680.49", mobile: "Feature phone" },
  { image: "https://robohash.org/quooccaecatiad.png?size=100x100&set=set1", name: "Theodora Jerromes", color: "Violet", hex_color: "#5e26cf", money: "$246.75", mobile: "Android 4.3" },
  { image: "https://robohash.org/nihilatdebitis.png?size=100x100&set=set1", name: "Scarlet Tellenbach", color: "Fuscia", hex_color: "#f3639c", money: "$754.24", mobile: "Feature phone" },
  { image: "https://robohash.org/accusantiumasperiorespariatur.png?size=100x100&set=set1", name: "Hermy Bertlin", color: "Red", hex_color: "#cf6433", money: "$544.97", mobile: "Android 8.0" },
  {
    image: "https://robohash.org/architectosequiperspiciatis.png?size=100x100&set=set1",
    name: "Meade McMurty",
    color: "Red",
    hex_color: "#6609dd",
    money: "$36.57",
    mobile: "Microsoft Windows Mobile 6.0 Professional",
  },
  { image: "https://robohash.org/quofacerequis.png?size=100x100&set=set1", name: "Kathleen Drejer", color: "Puce", hex_color: "#918888", money: "$400.30", mobile: "Feature phone" },
  { image: "https://robohash.org/velitnonhic.png?size=100x100&set=set1", name: "Pippy Wilcinskis", color: "Crimson", hex_color: "#b486b7", money: "$898.55", mobile: "Firefox OS 2.2" },
  {
    image: "https://robohash.org/iustovoluptatesreprehenderit.png?size=100x100&set=set1",
    name: "Winna Janz",
    color: "Mauv",
    hex_color: "#7cb38f",
    money: "$369.26",
    mobile: "Android 2.2, up to 2.3, TouchWiz UI 3",
  },
  { image: "https://robohash.org/nemohiceligendi.png?size=100x100&set=set1", name: "Ebba Peirce", color: "Puce", hex_color: "#f2a154", money: "$311.19", mobile: "Android 4.4.2" },
  { image: "https://robohash.org/addoloribusdolorum.png?size=100x100&set=set1", name: "Farly Edgecombe", color: "Indigo", hex_color: "#a8a5b0", money: "$960.74", mobile: "Feature phone" },
  { image: "https://robohash.org/atqueveniamdolorem.png?size=100x100&set=set1", name: "Lay Jaime", color: "Turquoise", hex_color: "#a79a39", money: "$35.70", mobile: "Feature phone" },
  { image: "https://robohash.org/distinctioquiaesse.png?size=100x100&set=set1", name: "Leroi Davidow", color: "Goldenrod", hex_color: "#a6550a", money: "$352.78", mobile: "Android 4.1" },
  {
    image: "https://robohash.org/sedquirerum.png?size=100x100&set=set1",
    name: "Elsie Gidney",
    color: "Crimson",
    hex_color: "#f314e3",
    money: "$248.09",
    mobile: "Android 10, up to 11, OxygenOS 11.1.4.4",
  },
  { image: "https://robohash.org/laboriosammollitiadicta.png?size=100x100&set=set1", name: "Matthieu Toward", color: "Violet", hex_color: "#c26d07", money: "$424.92", mobile: "Feature phone" },
  { image: "https://robohash.org/sitdeseruntquis.png?size=100x100&set=set1", name: "Lesley Kersting", color: "Turquoise", hex_color: "#e6ec20", money: "$101.18", mobile: "Feature phone" },
  { image: "https://robohash.org/etsuscipitquo.png?size=100x100&set=set1", name: "Sunny Nossent", color: "Red", hex_color: "#6223bc", money: "$847.45", mobile: "Feature phone" },
  { image: "https://robohash.org/cumeligendianimi.png?size=100x100&set=set1", name: "Alleen Ballance", color: "Indigo", hex_color: "#78d504", money: "$699.26", mobile: "Feature phone" },
  { image: "https://robohash.org/sitestblanditiis.png?size=100x100&set=set1", name: "Bartolemo Herrema", color: "Mauv", hex_color: "#577bdf", money: "$427.80", mobile: "Android 4.4.4" },
  { image: "https://robohash.org/etnisiadipisci.png?size=100x100&set=set1", name: "Venita Drane", color: "Blue", hex_color: "#d0834f", money: "$221.15", mobile: "Feature phone" },
  { image: "https://robohash.org/consequaturautemassumenda.png?size=100x100&set=set1", name: "Myrvyn Pudsey", color: "Yellow", hex_color: "#7d5739", money: "$489.33", mobile: "Android 4.4.2" },
  { image: "https://robohash.org/doloresenimut.png?size=100x100&set=set1", name: "Clarance Moreland", color: "Teal", hex_color: "#efa56c", money: "$472.08", mobile: "Android 10, Magic UI 3.1" },
  { image: "https://robohash.org/laboriosamomnisat.png?size=100x100&set=set1", name: "Modestine Billiard", color: "Blue", hex_color: "#3ae465", money: "$284.49", mobile: "Feature phone" },
  { image: "https://robohash.org/adofficiisnesciunt.png?size=100x100&set=set1", name: "Dorella Wimlett", color: "Green", hex_color: "#0d2fb5", money: "$764.65", mobile: "Feature phone" },
  { image: "https://robohash.org/omnisliberoeos.png?size=100x100&set=set1", name: "Robby Boughton", color: "Fuscia", hex_color: "#4d6002", money: "$9.58", mobile: "Feature phone" },
  {
    image: "https://robohash.org/providenteligendivel.png?size=100x100&set=set1",
    name: "Flore Bloan",
    color: "Aquamarine",
    hex_color: "#9d7706",
    money: "$777.50",
    mobile: "Microsoft Windows Mobile 6.0 Professional",
  },
  { image: "https://robohash.org/quisidut.png?size=100x100&set=set1", name: "Gwendolyn Brockherst", color: "Crimson", hex_color: "#33feb8", money: "$28.62", mobile: "Feature phone" },
  { image: "https://robohash.org/totamettempora.png?size=100x100&set=set1", name: "Odelia Benian", color: "Violet", hex_color: "#8955cd", money: "$396.58", mobile: "Feature phone" },
  { image: "https://robohash.org/sedconsequatureum.png?size=100x100&set=set1", name: "Carmelia Cuffe", color: "Violet", hex_color: "#4161c9", money: "$247.44", mobile: "Proprietary OS" },
  {
    image: "https://robohash.org/voluptatibusmolestiaesequi.png?size=100x100&set=set1",
    name: "Keith Hasnip",
    color: "Khaki",
    hex_color: "#840d48",
    money: "$699.75",
    mobile: "Android 2.1, up to 2.2",
  },
  { image: "https://robohash.org/doloribusquibusdamratione.png?size=100x100&set=set1", name: "Moshe Truter", color: "Teal", hex_color: "#07436e", money: "$673.15", mobile: "Android 4.0.4" },
  { image: "https://robohash.org/quiexcepturiut.png?size=100x100&set=set1", name: "Conrad Ticehurst", color: "Orange", hex_color: "#ba14da", money: "$995.77", mobile: "Feature phone" },
  { image: "https://robohash.org/eumculpapossimus.png?size=100x100&set=set1", name: "Charlie Churchley", color: "Fuscia", hex_color: "#8f5eac", money: "$287.70", mobile: "Feature phone" },
  { image: "https://robohash.org/fugitconsequunturtempore.png?size=100x100&set=set1", name: "Boyd Jeste", color: "Blue", hex_color: "#9a22b7", money: "$229.59", mobile: "Android 4.1" },
  { image: "https://robohash.org/maximeabsuscipit.png?size=100x100&set=set1", name: "Zilvia Fullstone", color: "Blue", hex_color: "#b412ba", money: "$689.02", mobile: "Android 2.3" },
  { image: "https://robohash.org/quibusdamquamid.png?size=100x100&set=set1", name: "Sissie Marfield", color: "Turquoise", hex_color: "#270ad8", money: "$665.57", mobile: "Feature phone" },
  { image: "https://robohash.org/quivoluptatemlaudantium.png?size=100x100&set=set1", name: "Othella Symcock", color: "Indigo", hex_color: "#baef02", money: "$606.29", mobile: "Android 8.0, ZUI 3.9" },
  { image: "https://robohash.org/minusquiaducimus.png?size=100x100&set=set1", name: "Dela Sutcliff", color: "Pink", hex_color: "#8d389a", money: "$195.80", mobile: "Feature phone" },
  { image: "https://robohash.org/voluptatibusconsequaturalias.png?size=100x100&set=set1", name: "Seana Fells", color: "Violet", hex_color: "#9cff73", money: "$488.18", mobile: "Feature phone" },
  { image: "https://robohash.org/recusandaemolestiaemaiores.png?size=100x100&set=set1", name: "Judith Lunnon", color: "Purple", hex_color: "#9ac1e7", money: "$325.81", mobile: "Android 4.4.2" },
  {
    image: "https://robohash.org/aliquidullamdistinctio.png?size=100x100&set=set1",
    name: "Westley Rosling",
    color: "Goldenrod",
    hex_color: "#21c0e5",
    money: "$355.61",
    mobile: "Android 4.4.4, MIUI 9.2",
  },
  { image: "https://robohash.org/debitisfugadolor.png?size=100x100&set=set1", name: "Moselle Bearman", color: "Crimson", hex_color: "#4cf7d4", money: "$96.09", mobile: "Android 2.3" },
  { image: "https://robohash.org/omnissuntnon.png?size=100x100&set=set1", name: "Alistair Andress", color: "Purple", hex_color: "#6fac34", money: "$294.83", mobile: "Android Wear OS" },
  { image: "https://robohash.org/verovelitet.png?size=100x100&set=set1", name: "Rosalind Trayling", color: "Puce", hex_color: "#96a108", money: "$455.25", mobile: "Feature phone" },
  { image: "https://robohash.org/voluptatemquasesse.png?size=100x100&set=set1", name: "Rupert Damant", color: "Red", hex_color: "#e1bfca", money: "$358.81", mobile: "BlackBerry OS 10.3.1" },
  { image: "https://robohash.org/quiquienim.png?size=100x100&set=set1", name: "Arney Casaroli", color: "Khaki", hex_color: "#1fef53", money: "$266.78", mobile: "Android 5.1" },
  {
    image: "https://robohash.org/nihilveniamitaque.png?size=100x100&set=set1",
    name: "Theresita Viner",
    color: "Goldenrod",
    hex_color: "#b4e345",
    money: "$923.87",
    mobile: "Android 10, EMUI 11, no Google Play Services",
  },
  { image: "https://robohash.org/atetpraesentium.png?size=100x100&set=set1", name: "Esteban Champagne", color: "Aquamarine", hex_color: "#1524c3", money: "$559.10", mobile: "Android 4.1" },
  { image: "https://robohash.org/estquoad.png?size=100x100&set=set1", name: "Enrika Benjamin", color: "Red", hex_color: "#b5e301", money: "$295.90", mobile: "Feature phone" },
  { image: "https://robohash.org/enimsuscipitin.png?size=100x100&set=set1", name: "Elyssa Impy", color: "Orange", hex_color: "#b9e3f1", money: "$729.51", mobile: "Feature phone" },
  { image: "https://robohash.org/siteatenetur.png?size=100x100&set=set1", name: "Leila Kittel", color: "Purple", hex_color: "#fde208", money: "$483.18", mobile: "Android 6.0" },
  { image: "https://robohash.org/eteteos.png?size=100x100&set=set1", name: "Kane Walaron", color: "Crimson", hex_color: "#2aa6d7", money: "$992.63", mobile: "Microsoft Windows Phone 8, up to 8.1" },
  { image: "https://robohash.org/minimadolorqui.png?size=100x100&set=set1", name: "Sophie Spaule", color: "Mauv", hex_color: "#b80a74", money: "$560.00", mobile: "Feature phone" },
  { image: "https://robohash.org/commodiperferendisdolorem.png?size=100x100&set=set1", name: "Tonie Felder", color: "Teal", hex_color: "#d6801d", money: "$575.76", mobile: "Feature phone" },
  { image: "https://robohash.org/consequunturarchitectoquia.png?size=100x100&set=set1", name: "Teodor Testro", color: "Crimson", hex_color: "#421833", money: "$477.20", mobile: "Feature phone" },
  { image: "https://robohash.org/nemoistecommodi.png?size=100x100&set=set1", name: "Porter Ansteys", color: "Aquamarine", hex_color: "#1db37d", money: "$831.71", mobile: "Tizen OS 2.3.2" },
  { image: "https://robohash.org/nequelaborumvoluptatem.png?size=100x100&set=set1", name: "Cesya Dakers", color: "Teal", hex_color: "#c06607", money: "$776.86", mobile: "Feature phone" },
  { image: "https://robohash.org/commodivoluptatesperferendis.png?size=100x100&set=set1", name: "Abbott Johnsee", color: "Violet", hex_color: "#16c5bf", money: "$522.60", mobile: "Android 2.3" },
  { image: "https://robohash.org/accusamussedquia.png?size=100x100&set=set1", name: "Esdras Iacobetto", color: "Turquoise", hex_color: "#3082b1", money: "$580.45", mobile: "Android 7.0" },
];
