const container = document.createElement("div");
container.style.border = "1px solid black";
container.style.backgroundColor = "yellow";
container.style.width = "800px";
container.style.height = "500px";

const box1 = document.createElement("button");
box1.innerHTML = "button";
box1.style.width = "100px";
box1.style.height = "50px";
box1.style.borderRadius = "30px";
box1.style.border = "none";
box1.style.margin = "10px";
box1.style.backgroundColor = "#2980b9";
box1.style.color = "white";
box1.style.fontSize = "17px";
document.body.appendChild(box1);

const box2 = document.createElement("button");
box2.innerHTML = "button";
box2.style.width = "150px";
box2.style.height = "50px";
box2.style.borderRadius = "30px";
box2.style.border = "none";
box2.style.margin = "10px";
box2.style.backgroundColor = "#2980b9";
box2.style.color = "white";
box2.style.fontSize = "17px";
document.body.appendChild(box2);

const box3 = document.createElement("button");
box3.innerHTML = "button";
box3.style.width = "200px";
box3.style.height = "50px";
box3.style.borderRadius = "30px";
box3.style.border = "none";
box3.style.margin = "10px";
box3.style.backgroundColor = "#2980b9";
box3.style.color = "white";
box3.style.fontSize = "17px";
document.body.appendChild(box3);

const box4 = document.createElement("button");
box4.innerHTML = "button";
box4.style.width = "100px";
box4.style.height = "50px";
box4.style.borderRadius = "30px";
box4.style.border = "none";
box4.style.margin = "10px";
box4.style.backgroundColor = "#3498db";
box4.style.color = "white";
box4.style.fontSize = "17px";
document.body.appendChild(box4);

const box5 = document.createElement("button");
box5.innerHTML = "button";
box5.style.width = "150px";
box5.style.height = "50px";
box5.style.borderRadius = "30px";
box5.style.border = "none";
box5.style.margin = "10px";
box5.style.backgroundColor = "#3498db";
box5.style.color = "white";
box5.style.fontSize = "17px";
document.body.appendChild(box5);

const box6 = document.createElement("button");
box6.innerHTML = "button";
box6.style.width = "200px";
box6.style.height = "50px";
box6.style.borderRadius = "30px";
box6.style.border = "none";
box6.style.margin = "10px";
box6.style.backgroundColor = "#3498db";
box6.style.color = "white";
box6.style.fontSize = "17px";
document.body.appendChild(box6);

const box7 = document.createElement("button");
box7.innerHTML = "button";
box7.style.width = "100px";
box7.style.height = "50px";
box7.style.borderRadius = "30px ";
box7.style.border = "1px solid #2980b9";
box7.style.margin = "10px";
box7.style.backgroundColor = "#ecf0f1";
box7.style.color = "#2980b9";
box7.style.fontSize = "17px";
document.body.appendChild(box7);

const box8 = document.createElement("button");
box8.innerHTML = "button";
box8.style.width = "150px";
box8.style.height = "50px";
box8.style.borderRadius = "30px";
box8.style.border = "1px solid #2980b9";
box8.style.margin = "10px";
box8.style.backgroundColor = "#ecf0f1";
box8.style.color = "#2980b9";
box8.style.fontSize = "17px";
document.body.appendChild(box8);

const box9 = document.createElement("button");
box9.innerHTML = "button";
box9.style.width = "200px";
box9.style.height = "50px";
box9.style.borderRadius = "30px";
box9.style.border = "1px solid #2980b9";
box9.style.margin = "10px";
box9.style.backgroundColor = "#ecf0f1";
box9.style.color = "#2980b9";
box9.style.fontSize = "17px";
document.body.appendChild(box9);

const box10 = document.createElement("button");
box10.innerHTML = "button";
box10.style.width = "100px";
box10.style.height = "50px";
box10.style.borderRadius = "30px";
box10.style.border = "none";
box10.style.margin = "10px";
box10.style.backgroundColor = "#bdc3c7";
box10.style.color = "white";
box10.style.fontSize = "17px";
document.body.appendChild(box10);

const box11 = document.createElement("button");
box11.innerHTML = "button";
box11.style.width = "150px";
box11.style.height = "50px";
box11.style.borderRadius = "30px";
box11.style.border = "none";
box11.style.margin = "10px";
box11.style.backgroundColor = "#bdc3c7";
box11.style.color = "white";
box11.style.fontSize = "17px";
document.body.appendChild(box11);

const box12 = document.createElement("button");
box12.innerHTML = "button";
box12.style.width = "200px";
box12.style.height = "50px";
box12.style.borderRadius = "30px";
box12.style.border = "none";
box12.style.margin = "10px";
box12.style.backgroundColor = "#bdc3c7";
box12.style.color = "white";
box12.style.fontSize = "17px";
document.body.appendChild(box12);

container.appendChild(box1);
document.body.appendChild(container);
